/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param headline 
 * @param level 
 * @param parentId 
 */
@Serializable@Serializable

data class Category (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "headline") @Required val headline: kotlin.String,

    @SerialName(value = "level") @Required val level: kotlin.Int,

    @SerialName(value = "parentId") val parentId: kotlin.Int? = null

) {


}

