/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.example.api.apis.DefaultApi
import com.example.api.models.Category
import com.example.api.models.Error
import com.example.api.models.Product

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test categoriesGet
        should("test categoriesGet") {
            // uncomment below to test categoriesGet
            //val result : kotlin.collections.List<Category> = apiInstance.categoriesGet()
            //result shouldBe ("TODO")
        }

        // to test productsGet
        should("test productsGet") {
            // uncomment below to test productsGet
            //val result : kotlin.collections.List<Product> = apiInstance.productsGet()
            //result shouldBe ("TODO")
        }

    }
}
