/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.example.api.models.Category

class CategoryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Category
        //val modelInstance = Category()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `headline`
        should("test headline") {
            // uncomment below to test the property
            //modelInstance.headline shouldBe ("TODO")
        }

        // to test the property `level`
        should("test level") {
            // uncomment below to test the property
            //modelInstance.level shouldBe ("TODO")
        }

        // to test the property `parentId`
        should("test parentId") {
            // uncomment below to test the property
            //modelInstance.parentId shouldBe ("TODO")
        }

    }
}
