/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param imageUrlThumb 
 * @param imageUrlLarge 
 */
@Serializable@Serializable

data class MainImage (

    @SerialName(value = "imageUrlThumb") @Required val imageUrlThumb: kotlin.String,

    @SerialName(value = "imageUrlLarge") @Required val imageUrlLarge: kotlin.String

) {


}

